project_id = "ylzscfeppxkgnmyvgqtc"

[functions.summarize-field]
verify_jwt = false

[functions.gee-analysis]
verify_jwt = false

[functions.enhanced-field-summary]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.elevenlabs-speech]
verify_jwt = false

[functions.health-check]
verify_jwt = false